### ISSUE TITLE
annie/dark was just mostly stolen from an existing theme

### ISSUE THREAD

**Issue by CanadaHonk** [c-um/anniedark#1]
Matches almost 1 to 1. https://github.com/swaroop3108/dark-dc/blob/master/source.css

**Comment by c-um** [comment]
Looks like it's a bit brighter on some parts? Never heard of dark-dc theme so didn't know that it was anything like annie/dark

**Comment by CanadaHonk** [comment]
annie/dark copied it, it isn't like it. It had identical comments and code.

**Comment by c-um** [comment]
Weird that they would steal it and make it a build override for "testing", average Discord moment.

**Comment by CanadaHonk** [comment]
It was probably just made by one employee for them/friends and wasn't meant to be public lol.

**Comment by c-um** [comment]
Added comments in the README.md and CSS pointing to the dark-dc theme and swaroop3108. Thanks for the info about dark-dc

**Comment by CanadaHonk** [comment]
Nice, all good.
